#cloud-config

ssh_authorized_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDLj1YJGwgQBPom2phPwoNOT4i5ZBzkpcoYYj+j1RPPansDmNQo9iUQG9e9TfvX5UDvymPpbFPZpJ+2aW/vYUWelgdnTqc8oEwK5tcF+ClRqeiPBmLbtLLBRF2Qyc5CZcdw16eLP7eiBzozb+xz4GHC2PGlOwhmlzQolDAhY0APB0KWvpXQnz6Ay7cJorikmXzvTrFExEblXV+wLy9oAZa+hz6/pu0ghsM/SZHghVAJyZvjJn0IFSDvfGyoAbUrxD7gl7oSwPnzwGZL/6D8CbGt0gHV8+sCBXo7RuRFiBFpIAeAS5XEU3iKQU//mAH97gcO2Zt6vuRMvBc4m8FVcz91"
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCicUEoju7O7UVwY/alZ3JVS/03C+ldA38O9ty5wdKK67WWNK9fQkUxffbDTSf6ew9H79Y48po7mJXN3d8DjguQxNEVQdVykb6twBnLXZ+fGqRPxM/WtkofTaEjLdNMK8zyfOtEZlPZm8PR6fv/11w8EWB90vCGCuFAq7omioZgBY6DpIxqQ1chOBW/y3xowDYuWdQfOwRaU2A+iYYf7gEVzp9fN7zs3IMnukw6fwlKB9+QgdMNOPAl/IuWYewqGuWmZZfv6xDct4tGh75Xn+AtK3RGXN6y9OF3LYU9F+qO9/pFpcTg+RxjvRcn+l14MSX4XaIpzDyiAVOkIXXwqcEv"
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1Nqofl1bYbmGEkgmtuLfPsoUQrzaMEj2vDj+vaJ57/4hBv/NfTHfhWZIxkS75MtsO2LLORubiQB1meHezZcSmyhQlcaP9znTfpOOMMv+qGS4/4ycTvfYeg7a+uXE7nJoJcb20qPZox4QgafgnzWxBJ1qnGHkL4c76rhbzU5P5zLPJVragjhk9qMc1ZrAmvxQAORkSeSjW7Ed8QpOP0Q1DHIgAOvJg5SWSInUu3kMWpmWlaNTh7O13VEVD/EUfzT5R01OKOBdJc7PSFwao1aLYqVS4PIIrAg/4NMTl0OVrTQ0Kr8vyxqS6/mrExlxnUC3oL7wAnWojM6RuoPjWtzDD"
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFZ3w/lkLmMgjW0vAMW/i/CUM1Iq6ANDXmWTGn0T2zlsPbdx8TOXEw2FnvAWjdfE2eMobl9R1Yj5Pb2j9JAD4mobzq7aTDkA8hj1slwv91RHYnweNopgO/XoheKlBtjP87tUhjgBSOrFrZ8bVV8Wbt9ZeKtNoYpBYeHQFaxc2AgkXbZjMqwxT+o0DXgc2/2RImYGOW0Uwn7uEhUqdPng3M/VbKZPOto6C1uSWzF6IjuOU8BtWQs6b7cXqCEzSGT3eTZ5Ly9kBJRB/xVxajRTiFhiE4SsKM90n1Htn6iZbC+5RhH4bz5HAiUhPK739JXTy3GT2kmQK7K8kH42X9RAKB"
  - "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAmIua6Dhut/R1E7ZdSFKR3xGnS12zrOuYwMqNNnChG4xMIw4grj0RO4ahGlJmkImprZj8ZH7TXoCk6+Gvg/mNS0vGpSEmvZFjk+3PNZjQp8f2fKy6w33uIVJMCAlz5E+HGn1IiN5oP/c50YaXoH6lLrQpGIOn2rRbkqrrT7P1BarT5wVwicfX6ZBdpGX+kVrFoMRLv2WUUK+eGLMSmSwUjHeWjrzLq3g1Z9G+IQjXM9s0phaWcfhrdgO62bzY9+pjMMztf+IN14AeiPUCi6PybKcdJAP5TvS1CPIYOAJNuTCrbhyUjy158A6BUQX2ckGNS18Vq/plULOvWGoI4sX1Uw=="
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPw4Cya0TuM00ivUD4/LxfjVKlu5BLfDoloLtgf4UVh+IlElprOC0afmkMLaaWSFCYsPS2fEdJkxh/gYCvVqew5EbPScbcdvGgyoCdsVf/0LRMPbhhuCsr68/WYtbIq41ZOPFEBdCBHsk+r1FKIIoSB0Vk9H63MhCDxCzbrapietDMuj3L0pqhOEJFh7Svbfu9oM3ZUhGhhISHl2ZBc5gqIr8mZXpHPulz6hNq7EVqUXx/ft3j64CUvqYtwn1ZWzqLq9qjgLBBoKP5dUPb1kjf1rhNefYdY2o79q2bIOPPlJ1wL9U2XFkmIDdshlRc1ls5SNOFqASI4aKJXR4DhJ0v takanori@ruylopez.local"

write_files:
  - path: /etc/ssh/sshd_config
    permissions: 0600
    owner: root:root
    content: |
      # Use most defaults for sshd configuration.
      UsePrivilegeSeparation sandbox
      Subsystem sftp internal-sftp

      PermitRootLogin no
      AllowUsers core
      PasswordAuthentication no
      ChallengeResponseAuthentication no
